[package]
name = "revzen_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
rocket_sync_db_pools = {version = "0.1.0-rc.2", features = ["diesel_postgres_pool"]}
